DROP TABLE IF EXISTS "instances" CASCADE;
DROP TABLE IF EXISTS "chat_session_messages" CASCADE;
DROP TABLE IF EXISTS "chat_session_members" CASCADE;
DROP TABLE IF EXISTS "tags" CASCADE;
DROP TABLE IF EXISTS "objects" CASCADE;
DROP TABLE IF EXISTS "licenses" CASCADE;
DROP TABLE IF EXISTS "user_reports" CASCADE;
DROP TABLE IF EXISTS "ip_addresses" CASCADE;
DROP TABLE IF EXISTS "notifications" CASCADE;
DROP TABLE IF EXISTS "moderations" CASCADE;
DROP TABLE IF EXISTS "tokens" CASCADE;
DROP TABLE IF EXISTS "unverified_users" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP EXTENSION IF EXISTS "pg_trgm";
