DROP TABLE IF EXISTS "instances" CASCADE;
DROP TABLE IF EXISTS "tags" CASCADE;
DROP TABLE IF EXISTS "objects" CASCADE;
DROP TABLE IF EXISTS "licenses" CASCADE;
DROP TABLE IF EXISTS "tokens" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "unverified_users" CASCADE;
