apiVersion: v1
kind: Secret
metadata:
  name: butterfly-api-secrets
  namespace: butterfly-api
type: Opaque
stringData:
  DATABASE_URL: "postgres://butterflyapi:b2e0xr7p9pipa6cfrthfm37jb27080vl@localhost/Butterflydb"

  AWS_ACCESS_KEY_ID: 44f2d579042b4e7b9a958db7f1aa8951
  AWS_SECRET_ACCESS_KEY: db1f7b0e91d24d1c9552f3eaa5815e2b
  AWS_DEFAULT_REGION: "uk"
  AWS_ENDPOINT_URL: "https://s3.uk.io.cloud.ovh.net/"

  MAIL_EMAIL: "support@butterflyvr.net"
  MAIL_TOKEN: "FSUG9PNX9AYDFWX1"
