ALTER TABLE instances DROP COLUMN  IF EXISTS"ip";
ALTER TABLE instances DROP COLUMN IF EXISTS "port";
ALTER TABLE users DROP COLUMN IF EXISTS "identifier" CASCADE;
ALTER TABLE instances ADD COLUMN TOKEN_VALID BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE instances ADD COLUMN "client_token" BYTEA NOT NULL;
