ALTER TABLE instances ADD COLUMN TOKEN_VALID BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE instances ADD COLUMN "client_token" BYTEA NOT NULL;
ALTER TABLE instances DROP COLUMN "ip";
ALTER TABLE instances DROP COLUMN "port";
ALTER TABLE users DROP COLUMN "identifier" CASCADE;
